### ISSUE TITLE
How do I do a healthcheck on grpcbin?

### ISSUE THREAD

**Issue by kikito** [moul/grpcbin#34]
Hi, I want to setup grpcbin inside a testing env using a docker-compose file, along other services.

I would like to know if there's a healthcheck I can use to verify it is actually up and running (and not just that Docker has created the container).

For example, PostgreSQL provides a command-line utility called `pg_isready` which can be used like so:
```
services:
  postgresql:
    image: postgres:9.5
    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD", "pg_isready", "--dbname=my_db", "--username=my_user"]
      timeout: 10s
    restart: on-failure
    stop_signal: SIGKILL
```

Could something like `netcat` be used to this effect?
